ABOUT
--------

(c) 2013 Netherlands Organisation for Applied Scientific Research [TNO](http://www.tno.nl)

Idea and realization: [Stef van Buuren](http://www.stefvanbuuren.nl), Reinout Stoop and Anne-Marie Zuurmond

--------

### DISCLAIMER

Unauthorized or improper use of the website or its content may breach intellectual property rights, regulations in respect of privacy, publication and/or communication in the broadest sense of the word. You are responsible for everything you send from the website.

It is not allowed to disrupt the normal operation of this site or to undermine its integrity, which includes changing the content and hacking the website. TNO reserves the right to end, for whatever reason, the availability of the website and/or of certain services on the web page, or to restrict access to them.
Although TNO has exercised due care to ensure the correctness of the information as stated on the website, TNO does not accept any responsibility for it. All content is provided “as is” and “as available”. Decisions which you take on the basis of this information will be at your own expense and risk.
TNO does not give any guarantee in respect of the security of this website. Although

In geen enkel geval zijn TNO, haar bestuurders, directeuren en/of medewerkers aansprakelijk ten aanzien van directe en/of indirecte, immateriële of gevolgschade met inbegrip van gederfde winst of inkomsten en verlies aan contracten of orders, die op enigerlei wijze voortvloeit of verband houdt maar niet beperkt hoeft te zijn tot: 

1. defecten, virussen of overige onvolkomenheden aan apparatuur en andere software in verband met de toegang tot of het gebruik van deze website;
2. de informatie die op of via deze website wordt aangeboden;
3. het onderscheppen, wijzigen of oneigenlijk gebruik van informatie die aan TNO of
aan u wordt gezonden;
4. de werking of het niet-beschikbaar zijn van deze website;
5. misbruik van deze website; 
6. verlies van gegevens;
7. het downloaden of gebruiken van software die via deze website beschik- baar wordt gesteld; of aanspraken van derden in verband met gebruik van deze website.

De uitsluiting van aansprakelijkheid geldt ook indien TNO op de hoogte is gesteld van de mogelijkheid van het optreden van dergelijke schade.

--------

